apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive-benchmark-config
  namespace: monitoring
  labels:
    app.kubernetes.io/component: benchmarking
    app.kubernetes.io/instance: thanos-receive-benchmark
    app.kubernetes.io/name: thanos-receive-benchmark
data:
  config.yaml: |-
    url: http://thanos-receive.monitoring.svc.cluster.local:19291/api/v1/receive
    tenants:
      - name: default-tenant
        clients: 10
        reqs: 2
        timeseries:
          - name: up
            labels:
              - name: job
                cardinality: 5
              - name: instance
                cardinality: 10
          - name: kube
            labels:
            - name: job
              cardinality: 5
            - name: instance
              cardinality: 10
            - name: namespace
              cardinality: 10
            - name: pod
              cardinality: 15
            - name: container
              cardinality: 15
            - name: high_cardinality
              cardinality: 50

