apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.17.2
  name: thanos-receive
  namespace: monitoring
spec:
  endpoints:
    - port: http
      interval: 10s
      relabelings:
        - separator: /
          sourceLabels:
            - namespace
            - pod
          targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-receive
